name: publish
on:
  push:
    branches:
      - main
jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          #!/usr/bin/env bash

          target="mds"
          count=0
          echo "#AU Covid-19 Update" > docs/README.md
          for f in "$target"/*
          do
              echo $f
              if [[ ${f} != *"test"* ]]; then
                  cat "$f" >> docs/README.md
              fi
              count=$((count+1))
          done
          echo ""
          echo "Count: $count"
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          message: 'publish'

      - run: echo "ğŸ This job's status is ${{ job.status }}."